#Task 3: Catering Choices
attendees = int(input("Enter number of attendees: "))
print ("With that number of guess I would recomend:") 
if attendees >= 100: print("Large Hall")
else: print("conference room")
if attendees >= 100: choice=input("Do you want a dance flore or photo booth? ")
else: choice=input("Do you want a DJ or band? ")
print((choice), (" is a good choice"))
food=input("Do you want Vegetarian food? yes or no ")
if food == "yes": print (" I would recommend Veggie Delight Caterers")
else: print(" the best non vegetarian food is Gourmet Meals Caterers")
